### ISSUE TITLE
VxWorks 6.9 does not provide `uintmax_t` type

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#509]
**Describe the bug**
A new compiler error has appeared on the vxworks-6.9 build:
```
/home/jphickey/cfecfs/github/osal/ut_assert/src/utstubs.c: In function 'UT_Hook_GetArgPtr':
/home/jphickey/cfecfs/github/osal/ut_assert/src/utstubs.c:602: error: expected specifier-qualifier-list before 'uintmax_t'
```

**To Reproduce**
Build using the VxWorks 6.9 toolchain

**Expected behavior**
Should build successfully

**System observed on:**
VxWorks 6.9, gcc 4.3.3 on gs582w-cfelnx lab machine.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.
