### ISSUE TITLE
Potential aliasing warning in socket code

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#1159]
**Describe the bug**
When using certain compiler versions and optimization flags, the address conversions in `os-impl-bsd-sockets.c` may trigger warnings.

**To Reproduce**
Build using GCC 10.3 with `-O3 -fstrict-aliasing -Wstrict-aliasing=2` options

Example warning:
```
osal/src/os/portable/os-impl-bsd-sockets.c: In function ‘OS_SocketAddrFromString_Impl’:
osal/src/os/portable/os-impl-bsd-sockets.c:724:42: error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]
  724 |     Accessor = (OS_SockAddr_Accessor_t *)&Addr->AddrData;
      |                                          ^~~~~~~~~~~~~~~
```

**Expected behavior**
Should be clean.

**Code snips**
https://github.com/nasa/osal/blob/2a2defbb6b5ecc9a0f6d5af96ff73f88edc27327/src/os/portable/os-impl-bsd-sockets.c#L719

**System observed on:**
Ubuntu 21.04

**Additional context**
This is due to direct casting of the data, to be pedantically correct should probably memcpy the address value, rather than directly cast it, to be super safe.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.
