### PR TITLE
osal Integration candidate: 2021-01-19

### LINKED ISSUE #229: mqueue test program
OSAL should include a simple mqueue test program to validate that the user has the correct settings and permissions to create/open/close/delete mqueues. Often users stumble on mqueue configuration and it is more difficult to diagnose when it's wrapped in the entirety of OSAL/cFS.

### LINKED ISSUE #429: Use a better time representation in OS_stat call
**Is your feature request related to a problem? Please describe.**
The `OS_stat` call currently returns the file time as an `int32` member within the `os_fstat_t` structure, as defined here:

https://github.com/nasa/osal/blob/a66eb2dc00136a77779414452835bb6364d5e1fb/src/os/inc/osapi-os-filesys.h#L154

This isn't really documented in the API but the field is a traditional UNIX-style timestamp, which is seconds elapsed since Jan 1 1970 UTC.

This type of timestamp suffers from the "year 2038" bug, where the int32 value rolls over and becomes negative.  Although this is 18 years from now, at the timescales of space software development cycles, it is entirely possible that coding being developed now will still be in service at the time this happens, so it should be fixed sooner rather than later.

**Describe the solution you'd like**
There are two fixes needed:

1. use the `OS_time_t` representation as used in `OS_GetLocalTime` and `OS_SetLocalTime`.  This is just for consistency - shouldn't use a different representation of time as the other API calls do.
2. Fix the `OS_time_t` to accommodate larger timestamp values and/or use a different epoch (latter would be risk but keep the structure the same size).

**Additional context**
Discussion regarding use of this field in nasa/cfe#519

**Requester Info**
Joseph Hickey, Vantage Systems, Inc.

### LINKED ISSUE #577: Adding unit tests from with a unit test not a supported pattern
**Describe the bug**
Possibly related to #554 (reverted to v5.1.0-rc1 and they ran).  Adding tests after starting to run tests (adding a test within a test) is not a supported pattern, and they won't actually get run (they do get added to the front of the individual list, but the merged test list doesn't not handle them).

**To Reproduce**
Add a unit test from within a unit test, build/execute and the added unit test will not execute.

**Expected behavior**
Didn't know NOT to do this... just don't do it.

**Resolution**
Just don't do it.
Document limitations and proper usage.

**Code snips**
uttest.c - see the adding and merging

**System observed on:**
 - Hardware: cFS Dev Server
 - OS: Ubuntu 18.04
 - Versions checked latest integration candidate and v5.1.0-rc1, problem does not exist in v5.1.0-rc1

**Additional context**
#554 

**Reporter Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #591: TTF (test teardown failure) not reported in individual or full test summary
**Is your feature request related to a problem? Please describe.**
TTF only indicated during the test run, not included in the individual or full summary.

**Describe the solution you'd like**
Include TTF in summaries

**Describe alternatives you've considered**
FAIL/TSF/TTF are all failures...

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #685: File chmod test failing on RTEMS
**Describe the bug**
When running unit tests against the latest baseline, there is a new failure on RTEMS:

```
[BEGIN] 04 TestChmod
OS_FileOpen_Impl():111:open(/RAM/Filename1): Invalid argument
[ FAIL] 04.001 file-api-test.c:257 - status after creat = -1
[ FAIL] 04.002 file-api-test.c:259 - status after close = -16
```

**To Reproduce**
Build with unit tests and execute on RTEMS 4.11 + pc686 + QEMU as documented in README.  The chmod test fails.

**Expected behavior**
Test should pass.

**System observed on:**
RTEMS 4.11.3, pc686 BSP, running in QEMU

**Additional context**
Appears to be introduced in PR #665  

Reinforces need (again) for CI script that runs the RTEMS build.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### LINKED ISSUE #692: Incorrect assertions in network-api-test
**Describe the bug**
The test is not correctly checking the return value in a few places.  For example:

https://github.com/nasa/osal/blob/9407cdf0be77521d850c587c0f749779c4656c3e/src/tests/network-api-test/network-api-test.c#L129

https://github.com/nasa/osal/blob/9407cdf0be77521d850c587c0f749779c4656c3e/src/tests/network-api-test/network-api-test.c#L133

**To Reproduce**
Make the subject code return something other than OS_SUCCESS or OS_ERR_NOT_IMPLEMENTED.  Assert statement will still be true.

**Expected behavior**
Probably should be `actual == OS_SUCCESS || actual == OS_ERR_NOT_IMPLEMENTED`

**System observed on:**
N/A - inspection

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### LINKED ISSUE #699: Build broken on RTEMS 4.11
**Describe the bug**
A recent change has broken the build for RTEMS (again).  These are printf format warnings.

```
/home/joe/code/cfecfs/github/osal/src/tests/select-test/select-test.c: In function 'TestSelectSingleRead':
/home/joe/code/cfecfs/github/osal/src/tests/select-test/select-test.c:321:5: error: format '%d' expects argument of type 'int', but argument 6 has type 'uint32' [-Werror=format=]
     UtAssert_True(StateFlags == 0, "OS_SelectSingle() (%d) == None", StateFlags);
     ^
/home/joe/code/cfecfs/github/osal/src/tests/select-test/select-test.c:331:5: error: format '%d' expects argument of type 'int', but argument 6 has type 'uint32' [-Werror=format=]
     UtAssert_True(StateFlags == OS_STREAM_STATE_READABLE, "OS_SelectSingle() (%d) == OS_STREAM_STATE_READABLE",
     ^
/home/joe/code/cfecfs/github/osal/src/tests/select-test/select-test.c: In function 'TestSelectSingleWrite':
/home/joe/code/cfecfs/github/osal/src/tests/select-test/select-test.c:436:9: error: format '%d' expects argument of type 'int', but argument 6 has type 'uint32' [-Werror=format=]
         UtAssert_True(StateFlags == 0, "OS_SelectSingle() (%d) == None", StateFlags);
         ^
```

Appears to be added by PR #683 ....

**To Reproduce**
Build for RTEMS 4.11 per instructions and default config.  Build fails.

**Expected behavior**
Build should succeed.

**System observed on:**
Ubuntu 20.04 as build host for RTEMS 4.11.3 / pc686 BSP.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### LINKED ISSUE #718: Deprecate OS_fsBlocksFree and OS_fsBytesFree
**Is your feature request related to a problem? Please describe.**
As noted in #573 these functions return the value directly, which does double duty as an error code and therefore is limited to being `int32` - but this type is not big enough for large file systems.

**Describe the solution you'd like**
Deprecate these functions in favor of `OS_FileSysStatVolume()` added in PR #717, which returns the information as a OS_statvfs_t object containing all relevant information.

**Additional context**
References to these functions within OSAL tests need to be fixed/replaced, as well as references in CFE/apps.  This is a follow-on/completion of the fix for #573 / PR #717.  Deprecation has to be done separately because the new function needs to exist before the refs can be changed.

**Requester Info**
Joseph Hickey, Vantage Systems. Inc.

### LINKED ISSUE #722: update UT_SetDefaultReturnValue comment
While I agree with the new function name, the comments are duplicated from the (now deprecated) `UT_SetForceFail()`, I suggest a re-write of the comments for this important function.

https://github.com/nasa/osal/blob/d698a4d7ddc66826a4c7c287468b5f1aa6ca372f/ut_assert/inc/utstubs.h#L183

### LINKED ISSUE #724: Change UT_ClearForceFail to UT_ClearDefaultReturnValue
**Is your feature request related to a problem? Please describe.**
UT_SetForceFail was deprecated in favor of UT_SetDefaultReturnValue, so UT_ClearForceFail is no longer a mirror

**Describe the solution you'd like**
Change UT_ClearForceFail to UT_ClearDefaultReturnValue

**Describe alternatives you've considered**
None

**Additional context**
See also #722, the comments should be updated for UT_SetDefaultReturnValue and UT_ClearDefaultReturnValue

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #743: Implement a Security Policy
**Describe the bug**
Create a security policy for users on how to report security vulnerabilities.

**Expected behavior**
The security policy should instruct users on how to report security vulnerabilities and provide them additional contact information for questions and concerns. 

**Additional context**
Additional sections that may be included:
- What to expect security-wise such as what type of testing is done
- Address privacy concerns
- Supported versions
- License
- Known vulnerabilities

References to Public Security Policies:
https://github.com/thanos-io/thanos/security/policy
https://github.com/minhealthnz/nzcovidtracer-app/security/policy
https://github.com/odoo/odoo/security/policy

**Reporter Info**
Ariel Adams, ASRC Federal

### LINKED ISSUE #746: Output format string as debug message in OS_printf stub
**Is your feature request related to a problem? Please describe.**
OS_printf stub is silent, more helpful when debugging tests to see at minimum the format string

**Describe the solution you'd like**
Output the format string as a debug messae similar to CFE_EVS_SendEvent

**Describe alternatives you've considered**
Could put in a hook, but this is general and useful enough to add

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #753: Remove UT_CheckForOpenSockets
**Is your feature request related to a problem? Please describe.**
See also nasa/cFE#901, was used to check that unit tests closed sockets but is no longer applicable.

**Describe the solution you'd like**
Remove

**Describe alternatives you've considered**
None

**Additional context**
None

**Requester Info**
Jacob Hageman - NASA/GSFC

### LINKED ISSUE #757: Typo in osapi.h
**Describe the bug**
Typo in osapi.h causes compilation failure when included into a c++ file

**To Reproduce**
Include osapi.h into a c++ file

**Expected behavior**
Successful compilation

**Code snips**

The following line is missing its corresponding `extern "C" {` and fails to build under C++: 
https://github.com/nasa/osal/blob/89bd11a98fa529538a851139a5682bc7ac5b4373/src/os/inc/osapi.h#L97-L99

Appears to be introduced in https://github.com/nasa/osal/commit/f0bd42edb8d731c2ba899292b3fd8f56e0f5fcb4

**System observed on:**
Linux

**Reporter Info**
John N Pham, Northrop Grumman

### LINKED ISSUE #760: OSAL tests fails under various conditions
**Describe the bug**

osal_loader_UT would fail while running on the target, since the utmod/* files aren't installed along w/ the test executable to build/exe/*

In addition, under certain circumstances, the following tests may fail, i.e. if another user has run the tests and files are left in /dev/shm (the tests don't clean up the files):
file-api-test
select-test

**To Reproduce**
For the first case, run test out of build/exe/[cpu]

For the second case, run file-api-test/select-test once, chown the files under /dev/shm/RAM[N] to some other user, and run again.  

**Expected behavior**
Tests should succeed

**Code snips**

Should have an install line for the test modules here:
https://github.com/nasa/osal/blob/bfca5b21f5fc2032505256fc67ae974f53a2a319/src/unit-tests/osloader-test/CMakeLists.txt#L18-L20

Should test if actual directory is writable, not just if the parent tmp directory is writable,
https://github.com/nasa/osal/blob/bfca5b21f5fc2032505256fc67ae974f53a2a319/src/os/posix/src/os-impl-filesys.c#L156-L165

This alone wouldn't solve the issue though, just punt it to the next available tmp directory. You'd probably also want to use mkstemp() or similar to generate a randomly named directory under the tmp folder. 

**System observed on:**
 - Linux

**Reporter Info**
John N Pham, Northrop Grumman

### LINKED ISSUE #761: TestReadWriteLseek has off by one error
**Describe the bug**
TestReadWriteLseek calls strlen but fails to account for null terminator, causing garbage characters to be written to test log

**To Reproduce**
Build and run file-api-test
Depending on the contents of memory, bogus characters may be written to build/[arch]/default_[cpu]/Testing/Temporary/LastTest.log

**Expected behavior**
Valid characters in LastTest.log

**Code snips**
Should be `size = strlen(buffer)+1`
https://github.com/nasa/osal/blob/bfca5b21f5fc2032505256fc67ae974f53a2a319/src/tests/file-api-test/file-api-test.c#L333

**System observed on:**
Linux

**Reporter Info**
John N Pham, Northrop Grumman

### PR DESCRIPTION
**Pull request by astrogeco**
**Describe the contribution**

Fix #746, Add UtDebug message from OS_printf stub
Fix #692, Resolve typos in unit test assert OR statements
Fix #577, Document nested tests not supported
Fix #753, Remove UT_CheckForOpenSockets
Fix #229, add mqueue functional test
Fix #757, Readd extern C in osapi.h to support C++ use
Fix #692, display message when not implemented error occurs
Fix #591, add test teardown failure to test summary
Fix #699, format printf correctly
Fix #685, change file create to use read write
Fix #748, add additional casts
Fix #743, Create Security Policy
Fix #429, update OS_time_t definition to 64  ticks
Fix #718, deprecate OS_fsBlocksFree and OS_fsBytesFree
Fix #761, Terminate string in TestReadWriteLseek
Fix #724, Refactor UT_ClearForceFail to UT_ClearDefaultReturnValue
Fix #722, update UT_SetDefaultReturnValue comments
Fix #229, mqueue test uses sequence of numbers
Fix #760, Install modules and clean up files for unit tests

**Testing performed**
See https://github.com/nasa/cFS/pull/177/checks

**Expected behavior changes**

PR #748 

PR #759    

PR #696  

PR #747  

PR #751  

PR #763  

PR #758  

PR #725  

PR #694  

PR #754  

PR #749  

PR #739

PR #695  

PR #735     

PR #764  

**System(s) tested on**
Ubuntu 18.04

**Additional context**
Part of https://github.com/nasa/cFS/pull/177/

**Third party code**
None

**Contributor Info - All information REQUIRED for consideration of pull request**
@jphickey 
@zanzaben 
@skliper 
@ArielSAdamsNASA

### CODE REVIEW

**Comment by astrogeco** [comment]
@skliper, 

Got a segfault after adding #747 


```
81/81 Test #81: sample_lib-sample_lib .............***Exception: SegFault  0.10 sec

96% tests passed, 3 tests failed out of 81

Total Test time (real) = 143.67 sec

The following tests FAILED:
	 69 - cfe-core_es_UT (Failed)
Errors while running CTest
	 71 - cfe-core_evs_UT (SEGFAULT)
	 81 - sample_lib-sample_lib (SEGFAULT)
Makefile:138: recipe for target 'test' failed
make: *** [test] Error 8
Error: Process completed with exit code 2.
```

See https://github.com/nasa/cFS/pull/177/checks?check_run_id=1742875628
