### PR TITLE
Fix #357: Make parameter const

### LINKED ISSUE #357: OS_ModuleLoad_Impl function header does not match definition
**Describe the bug**
When OS_INCLUDE_MODULE_LOADER is not defined, the function header does not
match the definition:

```
[ 98%] Building C object examples/rtems-cfs-hello-world/osal/CMakeFiles/osal.dir/src/os/rtems/osloader.obj
/home/andrei/Workspace/cFS/osal/src/os/rtems/osloader.c:320:7: error: conflicting types for 'OS_ModuleLoad_Impl'
 int32 OS_ModuleLoad_Impl ( uint32 module_id, char *translated_path )
       ^~~~~~~~~~~~~~~~~~
In file included from /home/andrei/Workspace/cFS/osal/src/os/rtems/os-rtems.h:39:0,
                 from /home/andrei/Workspace/on-board-software/vendor/cFS/osal/src/os/rtems/osloader.c:26:
/home/andrei/Workspace/cFS/osal/src/os/shared/os-impl.h:1230:7: note: previous declaration of 'OS_ModuleLoad_Impl' was here
 int32 OS_ModuleLoad_Impl ( uint32 module_id, const char *translated_path );
```

This issue was introduced in PR #21 .

**To Reproduce**
Build with `OS_INCLUDE_MODULE_LOADER` not defined.

**Expected behavior**
Build succeeds.

### PR DESCRIPTION
**Pull request by matzipan**
**Describe the contribution**
When OS_INCLUDE_MODULE_LOADER is not defined, the function header does not
match the definition. This issue was introduced in PR #21 .

Longer term: is there a continuous integration strategy to avoid this sort of situation happening in the future? 

**Testing performed**
Build with module loader disabled with cFS master distribution.

**Expected behavior changes**
None

**System(s) tested on**
 - PC, Ubuntu 19.04

**Contributor Info**
Andrei-Costin Zisu of Planetary Transportation Systems GmbH (Berlin, Germany). Company-wide CLA is in the process of being signed and should be available soon.

### CODE REVIEW

**Comment by skliper** [comment]
Good catch.  We are definitely planning to enhance our CI to catch more issues like this.  There are multiple opportunities for improvement (testing on multiple platforms, range of configuration settings, etc).  As a start see the matrix in https://github.com/nasa/cFS/pull/40.

Could you write a corresponding issue (and mark this pull as fixing it)?  Our contribution guide is still in work, but the preference is that pull requests have an associated issue they are implementing/solving.

Also, if you can let me know when the CLA is sent (email preferred) it'll expedite the process.

Thanks for contributing!

**Comment by matzipan** [comment]
> There are multiple opportunities for improvement (testing on multiple platforms, range of configuration settings, etc). As a start see the matrix in nasa/cFS#40.

We should discuss, we might lend a helping hand.

> Could you write a corresponding issue (and mark this pull as fixing it)? Our contribution guide is still in work, but the preference is that pull requests have an associated issue they are implementing/solving.

Opened #357 .

> Also, if you can let me know when the CLA is sent (email preferred) it'll expedite the process. 

Will push for it and will let you know.

**Comment by skliper** [comment]
CCB 20200122 - Reviewed and approved for IC (pending CLA)

**Comment by skliper** [comment]
Status update - We have received a CLA for cFE (18.128), but not OSAL (see https://github.com/nasa/osal/blob/master/doc/GSC_18370_Corp_CLA_form_1219.pdf).  Pull request pending receipt of OSAL CLA.

**Comment by stanislaw** [comment]
> Status update - We have received a CLA for cFE (18.128), but not OSAL (see https://github.com/nasa/osal/blob/master/doc/GSC_18370_Corp_CLA_form_1219.pdf). Pull request pending receipt of OSAL CLA.

This is true. We have noticed that on our side already but the person who is supposed to sign the OSAL CCLA is not there a few days. We will do it this week hopefully.

**Comment by stanislaw** [comment]
@skliper we have just signed the OSAL CCLA and sent it to to the GSFC-SoftwareRelease (Andrei Zisu and Stanislav Pankevich).

**Comment by skliper** [comment]
CLA for OSAL received, thanks!

**Comment by skliper** [comment]
@astrogeco Heads up this one is ready for merge to IC.
