### ISSUE TITLE
Reinstate RTEMS 4.11 build

### ISSUE THREAD

**Issue by jphickey** [nasa/osal#1441]
**Describe the bug**
The RTEMS 4.11 build fails because it does not implement `pthread_setname_np`.

**To Reproduce**
Build with RTEMS 4.11, error on call to `pthread_setname_np`

**Expected behavior**
Success

**System observed on:**
Debian with RTEMS 4.11 toolchain

**Additional context**
Although this OS is "obsolete" -- it still provides valuable feedback to the code quality, in particular because `int` and `long` map to different C fundamental types, and this exposes a number of coding/conversion errors.  Therefore it still serves as a good litmus test for how the code is likely perform on older architectures.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.
