### PR TITLE
Fix #509, Remove uintmax_t usage

### LINKED ISSUE #509: VxWorks 6.9 does not provide `uintmax_t` type
**Describe the bug**
A new compiler error has appeared on the vxworks-6.9 build:
```
/home/jphickey/cfecfs/github/osal/ut_assert/src/utstubs.c: In function 'UT_Hook_GetArgPtr':
/home/jphickey/cfecfs/github/osal/ut_assert/src/utstubs.c:602: error: expected specifier-qualifier-list before 'uintmax_t'
```

**To Reproduce**
Build using the VxWorks 6.9 toolchain

**Expected behavior**
Should build successfully

**System observed on:**
VxWorks 6.9, gcc 4.3.3 on gs582w-cfelnx lab machine.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Some systems may not provide this type.  Using `unsigned long` instead should be sufficient.

Fixes #509

**Testing performed**
Build on vxworks
Run all unit tests on native system and on RTEMS.

**Expected behavior changes**
No impact to behavior

**System(s) tested on**
Ubuntu 20.04
GSFC VxWorks lab build machine (gs582w-cfelnx)

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by jphickey** [comment]
> long long? Is an address ever returned (I'd think it could be).

It's in a union with a `void*` and `double`, so its got pointers and floating points covered already.  And AFAIK `long long` was also added around the same time as `uintmax_t`.

(FWIW even an old gcc 4.3.3 should definitely provide this type, I didn't dig into it much to see if there was perhaps some other reason it failed, but the regular `unsigned long` should be good enough so I left it at that)

**Comment by astrogeco** [comment]
CCB 2020-06-17: APPROVED
