### PR TITLE
Fix #1167, vxWorks intLib stub aliasing issue

### LINKED ISSUE #1167: Strict aliasing issue in vxWorks "intLib" stub
**Describe the bug**
When compiling with strict aliasing mode (gcc w/ `-O3 -fstrict-aliasing -Wstrict-aliasing=2`), a warning gets triggered in `vxworks-intLib-stubs.c` as follows:

```
osal/src/unit-test-coverage/ut-stubs/src/vxworks-intLib-stubs.c: In function ‘OCS_INUM_TO_IVEC’:
osal/src/unit-test-coverage/ut-stubs/src/vxworks-intLib-stubs.c:60:61: error: dereferencing type-punned pointer might break strict-aliasing rules [-Werror=strict-aliasing]
   60 |         UT_GetDataBuffer(UT_KEY(OCS_INUM_TO_IVEC), (void **)&VecTbl, &VecTblSize, NULL);
      |                                                             ^~~~~~~
cc1: all warnings being treated as errors
```

**To Reproduce**
Build with new-ish gcc (10.3) w/ `-O3 -fstrict-aliasing -Wstrict-aliasing=2` options and tests enabled (so stubs are built).

**Expected behavior**
Should be clean.

**System observed on:**
Ubuntu

**Additional context**
Could be argued that stubs should not be built with optimization+strict aliasing rules, but the fix is relatively easy to avoid this warning.

**Reporter Info**
Joseph Hickey, Vantage Systems, Inc.

### PR DESCRIPTION
**Pull request by jphickey**
**Describe the contribution**
Use a separate local variable rather than casting to (void **).

Fixes #1167 

**Testing performed**
Build with strict aliasing, confirm no warnings

**Expected behavior changes**
None

**System(s) tested on**
Ubuntu

**Contributor Info - All information REQUIRED for consideration of pull request**
Joseph Hickey, Vantage Systems, Inc.

### CODE REVIEW

**Comment by astrogeco** [comment]
https://github.com/nasa/cFS/wiki/Community-CCB-Agenda:-September-29-2021 APPROVED
- Figure out how to use CI to compile with even stricter warnings
